// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
import { projects } from "npm:@/data/mockData";
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List installation/site-survey/transport projects tracked in StaffPlanner. Optional filters by status, project type, client, and assigned installer id.",
  inputSchema: {
    status: z.enum(["open", "scheduled", "in-progress", "completed", "on-hold", "cancelled"]).optional().describe("Filter by project status."),
    projectType: z.enum(["installation", "site-survey", "transport"]).optional().describe("Filter by project type."),
    client: z.string().optional().describe("Filter by client name (case-insensitive substring)."),
    assigneeId: z.string().optional().describe("Return only projects assigned to this installer id."),
    unassignedOnly: z.boolean().optional().describe("If true, return only projects with no assignees."),
    limit: z.number().int().positive().optional().describe("Max results (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status, projectType, client, assigneeId, unassignedOnly, limit }) => {
    let rows = projects.slice();
    if (status) rows = rows.filter((p) => p.status === status);
    if (projectType) rows = rows.filter((p) => p.projectType === projectType);
    if (client) {
      const needle = client.toLowerCase();
      rows = rows.filter((p) => p.client.toLowerCase().includes(needle));
    }
    if (assigneeId) rows = rows.filter((p) => p.assigneeIds.includes(assigneeId));
    if (unassignedOnly) rows = rows.filter((p) => p.assigneeIds.length === 0);
    const capped = rows.slice(0, limit ?? 50);
    return {
      content: [{ type: "text", text: JSON.stringify(capped, null, 2) }],
      structuredContent: { count: capped.length, total: rows.length, projects: capped }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { projects as projects2 } from "npm:@/data/mockData";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project",
  description: "Fetch a single project by its id, including schedule, contact, and assigned installer ids.",
  inputSchema: {
    id: z2.string().min(1).describe("Project id, e.g. 'proj-1'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const project = projects2.find((p) => p.id === id);
    if (!project) {
      return { content: [{ type: "text", text: `No project with id ${id}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(project, null, 2) }],
      structuredContent: { project }
    };
  }
});

// src/lib/mcp/tools/list-installers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { installers } from "npm:@/data/mockData";
var list_installers_default = defineTool3({
  name: "list_installers",
  title: "List installers",
  description: "List all installers (staff and sub-vendors) available in StaffPlanner.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(installers, null, 2) }],
    structuredContent: { count: installers.length, installers }
  })
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { clients } from "npm:@/data/mockData";
var list_clients_default = defineTool4({
  name: "list_clients",
  title: "List clients",
  description: "List all retail clients StaffPlanner works with.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(clients, null, 2) }],
    structuredContent: { count: clients.length, clients }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "staffplanner-mcp",
  title: "StaffPlanner MCP",
  version: "0.1.0",
  instructions: "Read-only tools for StaffPlanner, a retail installation scheduling app. Use list_projects to browse projects (filter by status, type, client, assignee, or unassigned). Use get_project for a single project by id. Use list_installers and list_clients for reference data.",
  tools: [list_projects_default, get_project_default, list_installers_default, list_clients_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
