// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauth() {
  return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List installation/site-survey/transport projects from StaffPlanner. Optional filters by status, project type, client name, assigned installer id, and unassigned-only. Reads from live database; RLS applies.",
  inputSchema: {
    status: z.enum(["open", "scheduled", "in-progress", "completed", "on-hold", "cancelled"]).optional(),
    projectType: z.enum(["installation", "site-survey", "transport"]).optional(),
    client: z.string().optional().describe("Client name (case-insensitive substring)."),
    assigneeId: z.string().uuid().optional().describe("Installer id filter."),
    unassignedOnly: z.boolean().optional(),
    includeSandbox: z.boolean().optional().describe("Include sandbox rows (default false)."),
    limit: z.number().int().positive().max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, projectType, client, assigneeId, unassignedOnly, includeSandbox, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const sb = supabaseForUser(ctx);
    let q = sb.from("projects").select("*, clients(name), project_assignees(installer_id)").limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (projectType) q = q.eq("project_type", projectType);
    if (!includeSandbox) q = q.eq("sandbox", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let rows = data ?? [];
    if (client) {
      const needle = client.toLowerCase();
      rows = rows.filter((r) => (r.clients?.name ?? "").toLowerCase().includes(needle));
    }
    if (assigneeId) rows = rows.filter((r) => r.project_assignees?.some((a) => a.installer_id === assigneeId));
    if (unassignedOnly) rows = rows.filter((r) => (r.project_assignees ?? []).length === 0);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, projects: rows }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project",
  description: "Fetch a single project by id, with client, assignees, and transport stops. RLS applies.",
  inputSchema: { id: z2.string().uuid().describe("Project id (uuid).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("projects").select("*, clients(name), project_assignees(installer_id, installers(name)), transport_stops(*)").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No project with id ${id}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/list-installers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_installers_default = defineTool3({
  name: "list_installers",
  title: "List installers",
  description: "List installers (own staff and sub-vendors) from the live database. RLS applies.",
  inputSchema: {
    includeSandbox: z3.boolean().optional().describe("Include sandbox rows (default false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ includeSandbox }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const sb = supabaseForUser(ctx);
    let q = sb.from("installers").select("*");
    if (!includeSandbox) q = q.eq("sandbox", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, installers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_clients_default = defineTool4({
  name: "list_clients",
  title: "List clients",
  description: "List retail clients from the live database. RLS applies.",
  inputSchema: {
    includeSandbox: z4.boolean().optional().describe("Include sandbox rows (default false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ includeSandbox }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const sb = supabaseForUser(ctx);
    let q = sb.from("clients").select("*").order("name");
    if (!includeSandbox) q = q.eq("sandbox", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool5({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id, email, roles, and profile.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const sb = supabaseForUser(ctx);
    const uid = ctx.getUserId();
    const [{ data: profile }, { data: roles }] = await Promise.all([
      sb.from("profiles").select("*").eq("id", uid).maybeSingle(),
      sb.from("user_roles").select("role").eq("user_id", uid)
    ]);
    const payload = {
      user_id: uid,
      email: ctx.getUserEmail(),
      roles: (roles ?? []).map((r) => r.role),
      profile
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "piubkkipultepevxbxuv";
var mcp_default = defineMcp({
  name: "staffplanner-mcp",
  title: "StaffPlanner MCP",
  version: "0.2.0",
  instructions: "Signed-in tools for StaffPlanner (retail installation scheduling). All tools act as the connected user and respect Row-Level Security. Use list_projects/get_project to browse work, list_installers/list_clients for reference data, and whoami to see your identity and roles.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, get_project_default, list_installers_default, list_clients_default, whoami_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
